Config.vehicles = {

    -- PDM


-- Starter Compacts
    {
        label = 'Vapid Astron',
        price = 45000,
        model = 'astron',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Dinka Sugoi',
        price = 40000,
        model = 'sugoi',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Bravado Buffalo STX',
        price = 50000,
        model = 'buffalo4',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Bravado Buffalo EVX',
        price = 55000,
        model = 'buffalo5',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Grotti Turismo Classic',
        price = 60000,
        model = 'turismo2',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
{
        label = 'Vapid Kanjo Custom',
        price = 35000,
        model = 'kanjo',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
{
        label = 'Dinka Blista',
        price = 30000,
        model = 'blista',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Weeny Issi Classic',
        price = 32000,
        model = 'issi2',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Benefactor Panto',
        price = 28000,
        model = 'panto',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Grotti Brioso R/A',
        price = 38000,
        model = 'brioso2',
        catgeory = 'Starter',
        dealershipLocationIndex = 1,
    },

    {
        label = 'Bravado Dominator TT',
        price = 850000,
        model = '23CDemonTTDurangoSN',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Bravado Vortex EV',
        price = 700000,
        model = '204sForgiChargerEV',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Declasse Tornado Lowrider',
        price = 600000,
        model = 'apachelowrider',
        catgeory = 'Xevy',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Invetero Coquette C9',
        price = 750000,
        model = 'c8c',
        catgeory = 'Sports',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Sentinel G80',
        price = 900000,
        model = 'cfesm3g80',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Declasse Voodoo Donk',
        price = 550000,
        model = 'DBchevycap86',
        catgeory = 'Xevy',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Albany Buccaneer GNX',
        price = 650000,
        model = 'DBrrgnx',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Declasse Vigero 69',
        price = 700000,
        model = 'ddc69maro',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Bravado Gauntlet Hellfire',
        price = 600000,
        model = 'dl16chal',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Obey Tailgater RS',
        price = 950000,
        model = 'dl20rs6',
        catgeory = 'Arrow',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Enus Cognoscenti GT',
        price = 1800000,
        model = 'dl22bengt',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Pfister Cayston Turbo',
        price = 1100000,
        model = 'dl22caygt',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Pfister Comet GT4',
        price = 1000000,
        model = 'dl22gt4rs',
        catgeory = 'Sports',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Zion Competition',
        price = 850000,
        model = 'dl22m4',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Obey Omnis RS5',
        price = 800000,
        model = 'dl22rs5',
        catgeory = 'Arrow',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Rebla X7',
        price = 900000,
        model = 'dl22x7',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Sentinel M2',
        price = 750000,
        model = 'dl23m2',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Bravado Bison TRX',
        price = 800000,
        model = 'dl23ramtrx',
        catgeory = 'Offroad',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Declasse Vigero ZL1',
        price = 650000,
        model = 'dl23zl1',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Benefactor Dubsta G63',
        price = 1500000,
        model = 'dl24g63',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Rebla X5',
        price = 950000,
        model = 'dl24x5m',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Vapid Dominator GT',
        price = 600000,
        model = 'dl25mustang',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Sentinel 530',
        price = 450000,
        model = 'dl530i22',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Progen Tyrant 570',
        price = 1800000,
        model = 'dl570s',
        catgeory = 'Super',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Pfister Nine11 GT3',
        price = 2200000,
        model = 'dl911gtrsr',
        catgeory = 'Super',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht M5',
        price = 1000000,
        model = 'dl2024m5',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Zion M8',
        price = 1200000,
        model = 'dlbmwm8prior',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Rebla XM',
        price = 1300000,
        model = 'DLBMWXM',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Benefactor C63',
        price = 850000,
        model = 'dlc63',
        catgeory = 'Merci',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Bravado Magnate',
        price = 650000,
        model = 'dlhcmagnum',
        catgeory = 'Lord',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Canis Trailhawk',
        price = 800000,
        model = 'dljeep20',
        catgeory = 'Zeek',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Emperor Lux LC',
        price = 950000,
        model = 'dllc500',
        catgeory = 'Anzen Auto',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Zion',
        price = 950000,
        model = 'dlm4adro',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht SC',
        price = 1300000,
        model = 'dlm5cs22',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht E34',
        price = 700000,
        model = 'dlm5e34',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Stance',
        price = 800000,
        model = 'dlm5stance',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Dinka Roadster MX',
        price = 300000,
        model = 'dlmiatana6',
        catgeory = 'Anzen Auto',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Gallivanter Baller',
        price = 1200000,
        model = 'dlrover22',
        catgeory = 'Moon Rover',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Dinka Jester MK5',
        price = 700000,
        model = 'dlsupramk5',
        catgeory = 'Anzen Auto',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Albany Primo CT5',
        price = 850000,
        model = 'GL_CT5',
        catgeory = 'Sports',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Benefactor 63',
        price = 1400000,
        model = 'GT63TopCar',
        catgeory = 'Merci',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Benefactor Dubsta GLE',
        price = 900000,
        model = 'hycgle',
        catgeory = 'SUV',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Sentinel F80',
        price = 750000,
        model = 'mkf80m3',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Annis Elegy R34',
        price = 1500000,
        model = 'r34hugo',
        catgeory = 'Zephyr',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Obey Omnis RS3',
        price = 650000,
        model = 'rsthree',
        catgeory = 'Arrow',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Annis Remus Q50',
        price = 450000,
        model = 'slowq50',
        catgeory = 'Anzen Auto',
        dealershipLocationIndex = 1,
    },
    {
        label = 'Ubermacht Sentinel 340',
        price = 550000,
        model = 'vanzm340i',
        catgeory = 'Bayer Motors',
        dealershipLocationIndex = 1,
    },

-- Cars Donor
    {
        label = 'Retro 765',
        price = 1400,
        model = 'tlla_retro765lt',
        catgeory = 'Retro 80s',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Retro Escort',
        price = 1400,
        model = 'tlla_retroesc',
        catgeory = 'Retro 80s',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Retro Cat',
        price = 1400,
        model = 'tlla_retrohc',
        catgeory = 'Retro 80s',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Retro Rover',
        price = 1400,
        model = 'tlla_retrorango',
        catgeory = 'Retro 80s',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Retro 6M',
        price = 1400,
        model = 'tlla_retrox6m',
        catgeory = 'Retro 80s',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Summer Benefactor Rino',
        price = 1400,
        model = 'tlla_sumbenz',
        catgeory = 'Summer',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Summer Lingo 2',
        price = 1400,
        model = 'tlla_lingo2',
        catgeory = 'Summer',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Summer Lingo',
        price = 1400,
        model = 'tlla_lingo',
        catgeory = 'Summer',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Summer Bravado',
        price = 1400,
        model = 'tlla_sumcharger',
        catgeory = 'Summer',
        dealershipLocationIndex = 2,
    },
    -- {
    --     label = 'July Buffalo 170',
    --     price = 1400,
    --     model = 'tlla_charjuly',
    --     catgeory = 'New',
    --     dealershipLocationIndex = 2
    -- },
    -- {
    --     label = 'July Rango Ghoul',
    --     price = 1400,
    --     model = 'tlla_durjuly',
    --     catgeory = 'New',
    --     dealershipLocationIndex = 2
    -- },
    {
        label = 'Ubermacht Zion J82',
        price = 1400,
        model = 'vc_m4g82adrowidebody',
        catgeory = 'New',
        dealershipLocationIndex = 2,
        modData = {
            {
                modType = 5, -- VMT_CHASSIS / Frame
                modIndex = 0, -- vc_m4g82adrowidebody_body
            },
        }
    },
    {
        label = 'Enus Jubilee K',
        price = 1400,
        model = 'DBcullinank',
        catgeory = 'New',
        dealershipLocationIndex = 2
    },
    {
        label = 'Pegassi Zentorno',
        price = 1800,
        model = 'DBrevueltokeyvany',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Buffalo S',
        price = 1800,
        model = 'soloredcat',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Buffalo B',
        price = 1400,
        model = '3rrtt20ch',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht U5 Comp',
        price = 1400,
        model = 'BMWM5',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Benefactor Glendale 6 Seater',
        price = 1400,
        model = 'lextylunifypatent',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Pfister Comet HS3',
        price = 1400,
        model = 'pgt322',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Vapid Contender Custom',
        price = 1400,
        model = 'ccdf350c',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Grotti La Grotti',
        price = 1400,
        model = 'rmodlaferrari',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht U8 Extreme',
        price = 1400,
        model = 's8nm8',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht Zion Pre',
        price = 1400,
        model = 'la_gx41',
        catgeory = 'LuxBull',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Stovyant',
        price = 1400,
        model = 'gsttmp1',
        catgeory = 'LuxBull',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Benefactor Apex Custom',
        price = 1400,
        model = 'la_prestige_mon',
        catgeory = 'Luxury',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Shadowstrike',
        price = 1400,
        model = 'torosvenatus',
        catgeory = 'LuxBull',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Principe RS V4',
        price = 1400,
        model = 'lc_rsv4',
        catgeory = 'Omaha',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Principe Lectro RR',
        price = 1400,
        model = 'lc_ghost',
        catgeory = 'Omaha',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Canis Rampage Extreme',
        price = 1400,
        model = 'pace_srr_extreme',
        catgeory = 'Zeek',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Progen Velocity',
        price = 1400,
        model = 'widekitprogen750',
        catgeory = 'McVelocity',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Buffalo Hell1',
        price = 1400,
        model = 'gstbhell1',
        catgeory = 'Swerve',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Benefactor Titan',
        price = 1400,
        model = 'DRcGT63x',
        catgeory = 'Merci',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Enus Nightfall WB',
        price = 1400,
        model = 'widekitghost',
        catgeory = 'Roller',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Albany Cavalcade X',
        price = 1400,
        model = 'gstcavxl1',
        catgeory = 'Caddi',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Coil Ion',
        price = 1400,
        model = 'rrraidenwide',
        catgeory = 'Swerve',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Pfister Comet S2',
        price = 1400,
        model = 'gstcs22',
        catgeory = 'Swerve',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Bison Hellfire X',
        price = 1400,
        model = 'bisonvrx',
        catgeory = 'Swerve',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Truffade Specter',
        price = 1400,
        model = 'DRcProX',
        catgeory = 'Super',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht Stratum M',
        price = 1400,
        model = 'fckitty2',
        catgeory = 'Sports',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht U6 Shark Custom',
        price = 1800,
        model = 'abfx6shark',
        catgeory = 'SUV',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Canis Bloodhawk',
        price = 1800,
        model = 'amwbhawk',
        catgeory = 'Slider',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Enus Kingsreach Custom',
        price = 1400,
        model = 'bacalarkeyvany',
        catgeory = 'Luxury',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Stampede XL',
        price = 1400,
        model = 'GODzDRAMTRXWAGON',
        catgeory = 'Truck',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Buffalo Hell1',
        price = 1800,
        model = 'gstkrobuffhell1',
        catgeory = 'Slider',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Grotti Cista Hycade',
        price = 1400,
        model = 'pistahycade',
        catgeory = 'Super',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Shitzu Reaper RR',
        price = 1400,
        model = 'wisedev-h2r',
        catgeory = 'Bike',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht U7',
        price = 1400,
        model = 'mobm23',
        catgeory = 'SUV',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Grotti Burosade',
        price = 1400,
        model = 'gstcns1',
        catgeory = 'SUV',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Grotti Burosade Armored',
        price = 30000,
        model = 'DBfepurosanguebeast',
        catgeory = 'Armored',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Benefactor Armored',
        price = 30000,
        model = 'DBcls63s',
        catgeory = 'Armored',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht U3 Armored',
        price = 30000,
        model = 'DBm3csg80complain',
        catgeory = 'Armored',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Benefactor Glendale Coupe',
        price = 1400,
        model = 'mrwheelchair',
        catgeory = 'SUV',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Canis Killer Hawk Glow',
        price = 1400,
        model = 'KillerHwak',
        catgeory = 'Off-Road',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Hellhound',
        price = 1800,
        model = 'demondurango',
        catgeory = 'Slider',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Bison XR Widebody Custom',
        price = 1400,
        model = '22trxwb',
        catgeory = 'Off-Road',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Enus Jubilee Widebody',
        price = 1400,
        model = 'amcullinan',
        catgeory = 'SUV',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Invetero Coquette C7',
        price = 1400,
        model = 'DBugcz06lsx',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Progen Venom 765',
        price = 1400,
        model = 'DBugc765lt',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Dinka Hondito 6',
        price = 1400,
        model = 'DBA1AccordS',
        catgeory = 'New',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Buffalo STX-S',
        price = 1400,
        model = 'smkcharger',
        catgeory = 'Juneteenth',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Benefactor Class',
        price = 1400,
        model = 'smkclass',
        catgeory = 'Juneteenth',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Bravado Hawk',
        price = 1400,
        model = 'smkhawk',
        catgeory = 'Juneteenth',
        dealershipLocationIndex = 2,
    },
    {
        label = 'Ubermacht Sentinel G80 X',
        price = 1400,
        model = 'smkg80',
        catgeory = 'Juneteenth',
        dealershipLocationIndex = 2,
    },
    -- Exclusive dealership
    {
        label = 'Cupid Elite',
        price = 30000000,
        model = 'f90db',
        catgeory = 'Street x Angel Pack',
        dealershipLocationIndex = 3,
        forcedLivery = 0
    },
    {
        label = 'Sweetra',
        price = 40000000,
        model = 'g63amg6x6',
        catgeory = 'Street x Angel Pack',
        dealershipLocationIndex = 3,
        forcedLivery = 0
    },
    {
        label = 'Blushify',
        price = 30000000,
        model = 'JRX5M',
        catgeory = 'Street x Angel Pack',
        dealershipLocationIndex = 3,
        forcedLivery = 0
    },
    {
        label = 'Noctra',
        price = 50000000,
        model = 'solom3g802',
        catgeory = 'Street x Angel Pack',
        dealershipLocationIndex = 3,
        forcedLivery = 0
    },
    {
        label = 'Velnox',
        price = 70000000,
        model = 'solocoldcat',
        catgeory = 'Street x Angel Pack',
        dealershipLocationIndex = 3,
        forcedLivery = 0
    },
    {
        label = 'Tenyra',
        price = 50000000,
        model = 'Mannyttsvj',
        catgeory = 'Street x Angel Pack',
        dealershipLocationIndex = 3,
        forcedLivery = 0
    },
     -- Dono Boat dealership
    {
        label = 'RX Sport',
        price = 1800,
        model = 'tlla_rboat',
        catgeory = 'Small Boats',
        dealershipLocationIndex = 4,
        forcedLivery = 1
    },
    {
        label = 'H2R Turbo Ski',
        price = 1800,
        model = 'tlla_jet',
        catgeory = 'Small Boats',
        dealershipLocationIndex = 4,
        forcedLivery = 1
    },
    {
        label = 'Grande 140',
        price = 2600,
        model = 'tlla_sr650',
        catgeory = 'Medium Boats',
        dealershipLocationIndex = 4,
        forcedLivery = 1
    },
    {
        label = 'Sunset Twin Jet',
        price = 2600,
        model = 'tlla_sr450',
        catgeory = 'Medium Boats',
        dealershipLocationIndex = 4,
        forcedLivery = 1
    },
    {
        label = 'Grand Voyager',
        price = 3400,
        model = 'tlla_pershing',
        catgeory = 'Large Boats',
        dealershipLocationIndex = 4,
        forcedLivery = 1
    },
    {
        label = 'Zecnomar S63',
        price = 3400,
        model = 'tlla_lamboat',
        catgeory = 'Large Boats',
        dealershipLocationIndex = 4,
        forcedLivery = 1
    },

    -- Offroad Dealership 

    {
        label = '850 Sportsman',
        price = 1400,
        model = 'clappedcaston',
        catgeory = '4 Wheelers',
        dealershipLocationIndex = 5,
        modData = {
            {
                modType = 44, -- VMT_CHASSIS / Frame
                modIndex = 0, -- vc_m4g82adrowidebody_body
            },
            {
                modType = 45, -- VMT_CHASSIS / Frame
                modIndex = 0, -- vc_m4g82adrowidebody_body
            },
        }
    },
    {
        label = 'Vultur 700R',
        price = 1400,
        model = 'raptor700r',
        catgeory = '4 Wheelers',
        dealershipLocationIndex = 5,
        modData = {
            {
                modType = 6, -- VMT_CHASSIS / Frame
                modIndex = 0, -- vc_m4g82adrowidebody_body
            },
            {
                modType = 10, -- VMT_CHASSIS / Frame
                modIndex = 0, -- vc_m4g82adrowidebody_body
            },
        }
    },
    {
        label = 'F250KX',
        price = 1100,
        model = 'dillkx250f',
        catgeory = 'Dirt Bikes',
        dealershipLocationIndex = 5,
    },
    {
        label = 'F250EXC',
        price = 1100,
        model = 'excf250',
        catgeory = 'Dirt Bikes',
        dealershipLocationIndex = 5,
    },
    {
        label = 'X3 Turbo',
        price = 1400,
        model = 'placox3',
        catgeory = 'SXS',
        dealershipLocationIndex = 5,
    },
    {
        label = 'KG1 250F',
        price = 1400,
        model = 'kg1smg',
        catgeory = 'Trucks',
        dealershipLocationIndex = 5,
        modData = {
            {
                modType = 42, -- VMT_CHASSIS / Frame
                modIndex = 0, -- vc_m4g82adrowidebody_body
            },
        }
    },
    {
        label = 'Velociraptor',
        price = 1400,
        model = 'swueypreraptor',
        catgeory = 'Trucks',
        dealershipLocationIndex = 5,
    },


    -- Regular Boat dealership
    {
        label = 'Seashark',
        price = 8000000,
        model = 'seashark3',
        catgeory = 'Small Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Suntrap',
        price = 9500000,
        model = 'suntrap',
        catgeory = 'Small Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Jetmax',
        price = 15500000,
        model = 'jetmax',
        catgeory = 'Medium Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Tropic',
        price = 16800000,
        model = 'tropic2',
        catgeory = 'Medium Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Dinghy II',
        price = 13800000,
        model = 'dinghy2',
        catgeory = 'Medium Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Dinghy',
        price = 14200000,
        model = 'dinghy',
        catgeory = 'Medium Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Speeder',
        price = 15100000,
        model = 'speeder',
        catgeory = 'Large Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Squalo',
        price = 20800000,
        model = 'squalo',
        catgeory = 'Large Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Toro',
        price = 21800000,
        model = 'toro',
        catgeory = 'Large Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Longfin',
        price = 24200000,
        model = 'longfin',
        catgeory = 'Large Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Marquis',
        price = 40300000,
        model = 'marquis',
        catgeory = 'Special Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Kraken',
        price = 350000000,
        model = 'submersible2',
        catgeory = 'Special Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
    {
        label = 'Avisa',
        price = 450000000,
        model = 'avisa',
        catgeory = 'Special Boats',
        dealershipLocationIndex = 6,
        forcedLivery = 0
    },
}
