Config = {}

-- 🌟 Select Inventory system: 'qb', 'ox', 'quasar' and 'esx'
Config.Inventory = "ox"

-- if using qb/esx inventory then change this to the name of your core
Config.Core = "qb-core"

-- if using ox inventory then change this to the name of your inventory
Config.InventoryName = "ox_inventory"

-- 🌟 Customize Your Game Phrases Below ✨
-- Feel free to add or change phrases to make your game unique! 🎮📝
Config.Games = {
    would_you_rather = {
        "Would you rather your Instagram followers or your grandparents see your nudes?",
        "Would you rather accidentally send a dirty text to your boss or a sexy voice mail to your mom?  ",
        "Would you rather attend school with your partner, or work in the same place?     ",
        "Would you rather be always on top or always on the bottom?             ",
        "Would you rather be caught having sex at your workplace or have your boss knowingly watch you have sex? ",
        "Would you rather be caught in the act by a police officer or your in-laws?",
        "Would you rather be great at sex and have a bad body figure or be bad at sex and have a great body figure?",
        "Would you rather be handcuffed or blindfolded during sex? ",
        "Would you rather be horny all the time or never be able to have an orgasm?  ",
        "Would you rather be kinky or romantic?  ",
        "Would you rather be naked on a beach with everyone else fully clothed, or fully clothed on a nude beach.",
        "Would you rather be on top or on bottom during sex?  ",
        "Would you rather be partnered with someone who has a low sex drive or someone who has a sex addiction?    ",
        "Would you rather bring another person in bed or cheat?          ",
        "Would you rather catch someone masturbating or be caught masturbating?     ",
        "Would you rather cheat on your partner and be caught or be cheated on and never be told?        ",
        "Would you rather cuddle all day, but not be able to sleep next to each other at night, or sleep in the same bed, but not be able to cuddle during the day?",
        "Would you rather date a hot person but not be able to have sex with them or date an ugly person that you can have sex with? ",
        "Would you rather date someone who had a crush on you or date your crush?",
        "Would you rather date someone who refuses to kiss you or someone who refuses to give you oral sex?   ",
        "Would you rather do a wet t-shirt contest or give someone a lap dance? ",
        "Would you rather do romantic things or try out some new kinky ideas? ",
        "Would you rather dominate or be dominated?                 ",
        "Would you rather end a first date with sex or with a passionate kiss?",
        "Would you rather fart during sex or burp while kissing?              ",
        "Would you rather get a job promotion or sleep with your hot colleague?   ",
        "Would you rather get a massage with peanut butter or maple syrup?  ",
        "Would you rather get a text from a one-night stand that says “I'm pregnant” or “I have an incurable STD”? ",
        "Would you rather get slapped in the face every time you thought about sex or sneeze continuously while having sex?   ",
        "Would you rather give a golden shower or receive one?  ",
        "Would you rather go swimming naked in the sea or nude sunbathe?  ",
        "Would you rather go to a swingers party or a party with a BDSM group?  ",
        "Would you rather go to the grocery store in your underwear or go to the beach nude?     ",
        "Would you rather have a cupboard full of sex toys or or one full of kinky outfits?",
        "Would you rather have a full time partner or a friend with benefits?     ",
        "Would you rather have a naked picture of you become an internet meme, or be caught on camera naked during a live newscast?   ",
        "Would you rather have a partner that’s very possessive and clingy, or have a partner that’s very negligent?  ",
        "Would you rather have a partner who is a saint or someone who is super freaky?       ",
        "Would you rather have a sexy voice or a sexy body?      ",
        "Would you rather have a threesome with two strangers or have sex with any one of your choice? ",
        "Would you rather have an orgy with complete strangers or have to have sex with all your exes? ",
        "Would you rather have angry sex or make up sex?             ",
        "Would you rather have average sex every day for the rest of your life or great sex once a year for the rest of your life? ",
        "Would you rather have fluorescent pubic hair or extra-long pubic hair? ",
        "Would you rather have good food or good sex?    ",
        "Would you rather have group sex with strangers or with all your exes?   ",
        "Would you rather have kinky sex involving melted chocolate or whipped cream?      ",
        "Would you rather have multiple orgasms that weren't so good or just one terrific orgasm?    ",
        "Would you rather have one partner or multiple partners?",
        "Would you rather have really adventurous sex or romantic sex for the rest of your life?  ",
        "Would you rather have sex in a car or in a tent?  ",
        "Would you rather have sex in a smelly bathroom or on a strangers stain-filled bed?",
        "Would you rather have sex in an airplane bathroom or in a fitting room at a store? ",
        "Would you rather have sex tools or veggies for self-love?",
        "Would you rather have sex with your clothes on for a year or never see your partner fully naked again?",
        "Would you rather have sex without love or love without sex? ",
        "Would you rather have steamy shower sex or sex in a bubble filled bathtub?",
        "Would you rather have to kiss every person you meet or never kiss your partner again? ",
        "Would you rather have to sing the 1# charting song every time you have sex or have sex with the 1# charting artist once?  ",
        "Would you rather have unbelievable sex that lasts ten minutes or average sex that lasts an hour? ",
        "Would you rather have uncontrollable gas for an entire month or wet yourself at work? ",
        "Would you rather have your hair pulled, or have your back scratched? ",
        "Would you rather have your partner dress as a lumberjack or a sharp-dressed executive? ",
        "Would you rather have your partner dress as a sexy librarian or an exotic dancer?",
        "Would you rather have your partner surprise you with a shopping spree, or with a plane ticket? ",
        "Would you rather have your sexual partner dirty talk or be completely silent during sex?",
        "Would you rather have your X-rated search history published or never be able to get excited watching an X-rated movie?",
        "Would you rather kiss someone in the dark or make out in a public setting?",
        "Would you rather lick someone’s chin or suck someone’s thumb? ",
        "Would you rather lick someone’s eyeball or suck someone’s toes? ",
        "Would you rather live in the Playboy Mansion or live at a strip club?",
        "Would you rather lose your sense of feeling during love making or lose your sense of taste? ",
        "Would you rather make out with your biggest crush for ten seconds or your siblings best friend for ten minutes?  ",
        "Would you rather make out with your celebrity crush or get paid $5,000?",
        "Would you rather make whoopee in your parents' bed or at a mattress store?",
        "Would you rather masturbate every day for the rest of your life or never be able to masturbate again?   ",
        "Would you rather only cuddle in the morning or only cuddle at night? ",
        "Would you rather pay or be paid to have sex?  ",
        "Would you rather play teacher's pet or play doctor?",
        "Would you rather receive a sexy text message or a sexy nude photo? ",
        "Would you rather receive an erotic letter or send a dirty text message? ",
        "Would you rather say your ex's name during sex or your partner's best friend's name? ",
        "Would you rather sleep with someone on the first date or wait for six months?",
        "Would you rather sleep with your partner’s siblings or your best friends sibling? ",
        "Would you rather smell like body odor for a year or have terrible acne for 6 months? ",
        "Would you rather suck at foreplay or suck at sex?",
        "Would you rather swallow or spit?",
        "Would you rather take a body shot off of me, or have me take a body shot off of you? ",
        "Would you rather talk dirty to me over the phone or through text/picture messages?",
        "Would you rather talk dirty with the person sitting to your left or to your right? ",
        "Would you rather tease with hot wax or with ice cubes?",
        "Would you rather walk in on your best friend naked, or have your best friend walk in on you naked?",
        "Would you rather walk in on your parents making love, or have them walk in on you?  ",
        "Would you rather watch your partner touch themselves or have them watch you touch yourself?” ",
        "Would you rather wear the same pair of underwear for a week or wear your mother’s clean underwear for a day?",
        "Would you rather whip or be whipped?",
        "Would you rather wrestle naked in a pool of Jell-O or chocolate pudding?",
        "Would you rather your neighbors see your genitals or accidentally send a sexy text message to a relative?  ",
        "Would you rather be with someone who loves to strip tease or who knows how to tease with their lips?",
        "Would you rather pick up someone from a nightclub or someone from a bar?",
        "Would you rather date a porn star or be a porn star? ",
        "Would you rather date a sex addict or a virgin? ",
        "Would you rather have foreplay and no sex, or sex without foreplay?",
        "Would you rather listen to dirty talk or listen to soft whispers during sex?",
        "Would you rather touch yourself or use a dildo in front of your partner?",
        "Would you rather listen to dirty talk or listen to soft whispers during sex?",
        "Would you rather be kissed all over or be kissed on the lips over and over?",
        "Would you rather give a handjob in public or get a hand job in public?  ",
        "Would you rather your partner found oral sex disgusting or was obsessed with anal sex? ",
        "Would you rather have drunk sex or stoned sex? ",
        "Would you and your lover rather watch your favorite porn stars in action or join in with them?",
        "Would you rather have rough sex all the time or have gentle sex all the time?",
        "Would you rather be a sex slave or a virgin for life?",
        "Would you rather do a nude photo shoot or wear something really sexy and revealing for a photo shoot? ",
        "Would you rather walk around the house in just your underwear or go out without underwear? ",
        "Would you rather have many one night stands or a single one year only relationship? ",
        "Would you rather grant everyone's sexual fantasies or make everyone's fantasies come true?  ",
        "Would you rather we sexted or Zoom sex?",
        "Would you rather sneeze every time you orgasm, or orgasm every time you sneeze?",
        "Would you rather have sex with a man dressed as a woman, or a woman dressed as a man? ",
        "Would you rather do it with protection or without? ",
        "Would you rather make out at the movies or in the backseat of a car? ",
        "Would you rather play naughty teacher or dirty doctor?",
        "Would you rather have sex in an igloo, or in a sauna? ",
        "Would you rather clog the toilet on a first date or first day at a new job?  ",
        "Would you rather say your ex's name during sex or your partner's best friend's name?  ",
        "Would you rather pay or be paid to have sex? ",
    },
    aboutme = {
        "What is your idea of a perfect date?",
        "What do you hate about dating the most?",
        "What is the best date you have ever been on?",
        "What is the most ridiculous date you have been on?",
        "What’s your favorite scent?",
        "What is the most ridiculous date you have been on?",
        "What’s the weirdest compliment you’ve ever received?",
        "Do you believe in soulmates?",
        "Are you a romantic person?",
        "Can a guy and a girl be friends without falling in love?",
        "What is your biggest turn off?",
        "What would you do if you became a boy/girl for a day?",
        "Do you believe in love at first sight?",
        "Would you rather have an endless supply of money or eternal love?",
        "What do you find most attractive in a boy or girl?",
        "If you could marry a fictional character, who would it be?",
        "How many girlfriends or boyfriends have you had before?",
        "Who was your first crush? How old were you?",
        "Are you Ticklish?",
        "If you could choose a celebrity to date, who would you pick?",
        "What age were you when you had your first kiss?",
        "Can you describe your first kiss?",
        "What is your favorite smell and why?",
        "What is the most romantic date idea for you?",
        "Would you rather go on a double date, or keep it one on one?",
        "Who is your celebrity crush?",
        "What are you most passionate about right now?",
        "Would you rather hug or hold hands in public?",
        "Would you snoop through your partner's phone?",
        "What is the most romantic movie you have ever seen?",
        "Would you rather receive flowers or candy?",
        "What is the most romantic song you have heard?",
        "What do you believe is the fastest way to someone's heart?",
        "After a breakup, do you try to remain friends, or do you cut them out of your life?",
        "Are you a trusting person?",
        "Have you ever told a lie in order to avoid hurting a partner's feelings?",
        "Have you ever been on a blind date?",
        "Do you prefer a to go out to dinner and a movie, or stay home with take out and a movie on tv?",
        "Do you have a nickname?",
        "Do you like to use pet names for your partner?  Which ones?",
        "If you could only keep four apps on your phone, what would they be?",
        "If money wasn't an issue, what type of career would you choose?",
        "What is the most embarrassing that happened to you as a teenager?",
        "Do you have a hidden talent?",
        "When you have had a bad day, what is your favorite way to relax?",
        "When you were a kid, what did you want to be when you grew up?",
        "What is your favorite thing to eat for breakfast?",
        "What movie do you think everyone should watch?",
        "What singer or band would you be ashamed to admit you enjoy?",
        "What tv show is your guilty pleasure?",
        "What is your biggest pet peeve?",
        "Would you rather live in the country or in the city?",
        "Could you survive without your phone for 24 hours?",
        "Describe the weirdest dream you have had.",
        "If you had your human body, but the head of an animal, what animal would you pick?",
        "Would you rather lose all of your money or all of your pictures?",
        "How long do you think you'd be able to live alone for?",
        "If you could instantly become an expert in something, what would it be?",
        "If you could eliminate one thing from your daily routine, what would it be and why?",
        "If you could be on a reality TV show, which one would you choose and why?"
    },
    fetish = {
        "Impact Play: Impact play means spanking, flogging, paddling, and other forms of consensual striking.",
        "Role-Playing: You don't have to stop playing make-believe when you grow up. Role-playing means acting out a sexual fantasy with your partner(s)",
        "Foot Fetish: A foot fetish involves a desire to worship feet through acts such as massage, kissing, and smelling.",
        "Anal Sex: You don't need to have an anal fetish to engage in anal sex, but plenty of people do specifically get off on butt stuff.",
        "Lingerie: Renye says that one of the most common fetishes centers on something that may be sitting inside your dresser right now: lingerie.",
        "Group Sex: Group sex is getting it on with more than one person.",
        "Sensation Play: Sensation play can refer to a huge range of activities based on the receiving or withholding of different stimuli.",
        "Orgasm Control: Edging, in which the submissive partner is brought to the brink of climax and then forced to stop — often done repeatedly — is an example of orgasm control.",
        "Bondage: Bondage is when one partner restrains the other.",
        "Psychological Play: Some of the most intense sexual play takes place in the mind. Renye refers to psychological power play — a type of BDSM — as mind control.",
        "Voyeurism and Exhibitionism: Voyeurism — or obtaining sexual pleasure from watching others who are naked or having sex — is more common than you'd think.",
        "Cuckolding: You may have heard the term cuck thrown around as an alt-right slur.",
        "Erotic Humiliation:lets you reclaim embarrassment by getting off on it. Humiliation play is a consensual power exchange that is a very typical fetish.",
        "Spectrophilia: Spectrophilia refers to having a thing for ghosts because sometimes humans aren't worth it.",
        "Dominance and Submission: Dominance and submission refer to a consensual erotic power exchange between two (or more) people.",
        "Autonepiophilia: Autonepiophilia means adult that act like babies.",
        "Urophilia: Urophilia is a fancy name for piss play, golden showers, and watersports.",
        "Sadism & Masochism: Sadism refers to a person, a sadist, who gets off on inflicting pain.",
        "Wax play: Wax play involves dripping hot candle wax on your lover.",
        "Vorarephilia: Vorarephilia is the infamous cannibal kink.",
        "Quirofilia: Quirofilia is one of those kinks that sounds more far-out than it is: It simply refers to an attraction to hands.",
        "Pregnancy: Yes, pregnancy can be the result of sex, but it can also turn people on.",
        "Tentacles: If you've ever gone into a porn search black hole, you may have stumbled upon anime tentacle porn.",
        "Age Play: Age play is easy to be creeped out at, but it's so common that you don't even realize it. If a lover has ever called you baby, you've engaged in age play.",
        "Stranger Play: If you've ever hooked up with a stranger, perhaps even before getting their name, congrats, you've tried stranger play.",
        "Emetophilia: Gag warning: Emetophilia is a sexual fetish in which one gets aroused by vomit.",
        "Klismaphilia: Klismaphilia is arousal from enemas.",
        "Electrostimulation: According to Richmond, electrostimulation is a pretty common kink.",
        "Cake farts: A girl is made to sit on the cake and then fart on it.",
        "Balloon fans: Some men love having balloons in their room while having sex.",
        "Formicophilia: Get your rocks off by being covered in insects.",
        "Furries: People who dress up in animal costumes.",
        "Objectophilia: objectophilia means taking love of objects to a whole new level.",
        "Autozoophilia: A fetish in which a person is aroused by the notion of seeing themselves as an animal.",
        "Macrophilia: When it comes to the debate over size, bigger is most definitely better for macrophiliacs, who are turned on by the idea of giants.",
        "Agalmatophilia: They are attracted to, and often maintain relationships with dolls or statues ",
        "Kleptolagnia: Wearing a pair of handcuffs is a relatively normal kink, but people with this fetish risk actually getting arrested.",
        "Erotic Lactation: is a sexual paraphilia where individuals (typically male) derive sexual pleasure from watching women lactate, sucking on women’s breasts",
        "Pegging: Traditionally, pegging refers to a cisgender, heterosexual male receiving anal penetration from his cishet female partner with a strap-on dildo",
        "Public sex: Well, it is public, right?",
        "Abasiophilia: This one is often described as a fetish for mobility aids such as braces, casts or wheelchairs",
        "Acousticophilia: Sexual arousal from specific sounds.",
        "Acrotomophilia: A sexual interest in amputees.",
        "Acucullophilia: A fetish for circumcised penises",
        "Agonophilia: Getting off on fake violence",
        "Algolagnia: Sadism or masochism: a fetish for inflicting pain on yourself or on others.",
        "Alvinolagnia: Sexual attraction to tummies.",
        "Androidism: A fetish for human-esque robots, or of humans pretending to be robots.",
        "Axillism: Is there anything better than gently putting your tongue or todger into the warm folds of… an armpit?",
        "Porn: Well, is that a fetish or a fear?",


    },
    morally = {
        "You find $20 on a bus seat. Do you ask around to see if anyone dropped it?",
        "If someone tells an offensive joke, is it your responsibility to speak up about it?",
        "You have a vague suspicion that your partner is having an affair and have discovered the password to their email account. Would you check their email?",
        "Would you rather be rich and paralyzed from the waist down or poor and able-bodied?",
        "Stealing is immoral, right?  But what if stealing was the only way to feed a starving child?",
        "If you were on holiday and you met someone attractive who you would never see again, would you invent stories to make yourself more interesting?",
        "Is it OK to fantasize about someone else when you are with your partner?",
        "You are an eyewitness to a crime: a man has robbed a bank, but instead of keeping the money for himself, he donates it to a poor orphanage that can now afford to feed, clothe, and care for its children.",
        "You know who committed the crime. If you go to the authorities with the information, there's a good chance the money will be returned to the bank, leaving a lot of kids in need. What do you do?",
        "If someone could tell you the exact day and time that you are going to die, would you want them to tell you?",
        "Your boss gives you credit for a project on which a colleague did most of the work. Should you accept the praise?",
        "Have you ever discriminated against someone?",
        "Imagine that a street gang notorious for wearing purple shirts has robbed and murdered several people in your town.  If a man wearing a purple shirt just rang your doorbell, would you answer it?",
        "Do the words ‘freedom’ and ‘liberty’ mean not being persecuted or discriminated against, or do they mean doing whatever you please?",
        "If you got to work and you discovered that you had put on two different shoes when you got dressed, would you go home to change?",
        "Is it unfair to move into better (open) seats at a sporting event or a concert?",
        "If you had a new partner who loved opera and you hated it, would you go to an opera with them to make a good impression?",
        "No matter how bad things get, are you aware that someone always has it worse than you do?",
        "Are you willing to sacrifice the life of your child or lover to support a war?",
        "If you were asleep on the train and an elderly person fell asleep on your shoulder, would you move?",
        "You are invited to your new partner's parents house for first time. They serve you liver at dinner. You hate liver. What would you do?",
        "Whilst out walking, you find a bag in a bush containing $50,000 which has been hidden there by a drug dealer who is currently in prison for 10 years. Would you keep the cash?",
        "You win a substantial amount of money on the lottery but a relative whom you dislike is in serious debt. Do you keep the win a secret from your whole family?",
        "When you help someone, do you ever think, “What’s in it for me?”",
        "If you dropped a new television, would you take it back to the shop and say it never worked?",
        "If you found a beautiful and expensive bracelet in the street, would you keep it?",
        "Is it considered stealing to take pens from a bank? What about extra napkins from a fast-food restaurant?",
        "You crash into another car in the parking lot. You are not insured. No one saw you. Would you drive away without leaving a note?",
        "If something at a yard sale or market is far more valuable than the posted price, do I have to let the seller know?",
        "You're about to serve food to guests at a dinner party, and you drop a serving or two on the floor. It’s salvageable, and no one sees. Do you still serve it?",
        "At school, your teacher wants to know who broke a window. She says if the person does not own up, the whole class will be punished. You know who it was. Do you tell?",
        "Would you tell someone if they had food remains on their face?",
        "You wear a new shirt once and decide you don't like it. Is it okay to return it—even though it’s been worn?",
        "You have been happily married for 10 years but discover that your partner appeared in several adult movies before you met. Could you forgive your partner for not telling you about their past?",
        "If someone offered you $500 for a necklace that you had bought for $50 would you accept?",
        "You are friends with a married couple and one of them confides in you that they are having an affair. Would you feel obliged to tell their partner or would you keep quiet?",
        "An 88 year-old man or woman invites you to spend the weekend with them as their lover. In return you will inherit their entire estate worth a small fortune. Would you accept their invitation?",
        "If you found out you were going to die today, would you have any regrets?  Would you be happy with the way you spent the last 24 hours of your life?",
        "You borrow the keys to your friend's sports car. While out driving you get flashed by a speed camera. You could lose your license as you have already been caught speeding twice before. What do you do?",
        "Is it okay to take a free sample of something, even though you know you won't buy it?",
        "You are shopping and notice a woman stuffing a pair of stockings into her purse. Do you report her?",
        "Should there be a death sentence?",
        "You pass someone in the street who is in severe need and you are able to help them at little cost to yourself. Are you morally obliged to do so?",
        "Is it okay to use work supplies or mail for personal purposes?",
        "Should the wealthier members of society be forced to pay through taxation, for the poorer members? If so, how much?",
        "You have accepted an invitation to a friend's party. Then you are invited to a much more fun party. Would you think of an excuse not to go to your friend's party?",
        "A rich man and a poor man commit the same type of crime. The rich man is fined $10,000 while the poor man is sent to jail for one year. Is this fair?",
        "You discover Bill Gates' wallet lying on the street. It contains $1000.00 Do you send it back to him?",
        "Would it be justifiable to whip pigs to death if more succulent pork resulted from this process, giving the consumers of pork more pleasure?",
        "Why punish the theft of $1000 more than the theft of $100?",
        "Your partner has left his/her email open on your shared computer. Is it okay to take a look at the inbox? What about at a specific email? ",
        "The clerk at the grocery store gives you too much change. Do you tell her?",
        "Would you rather be the most intelligent or the most attractive?",
        "My boss asked me to cover for him on his expense report by saying I was at a meal when I wasn't. Should I do it?",
        "If you found a diary that a friend had left at your house, would you read it?",
        "Would you rather be in a faithful relationship, but fight a lot with your partner, or in an unfaithful relationship but be very happy together?",
        "You can save the lives of ten innocent people by killing one innocent person. Are you morally obliged to do so?",
        "Is it ethical to grow fully formed, brainless clones for harvesting organs?",
        "Would you rather be extremely attractive and married to someone ugly or ugly and married to someone extremely attractive?",
        "Would you rather have your first child at 16 or 52 years old?",
        "If your best friend proudly gave you a picture she had painted and you didn't like the painting, would you put it on the wall in your house? ",
        "Would you rather be blind or deaf?",
        "If you are married in real life, does having a virtual sexual relationship online with someone else count as cheating?",
        "Should you ALWAYS tell the truth?"
    },
    couplesquiz = {
        "What initially attracted you to me?",
        "How do you define love in the context of our relationship?",
        "What is your favorite memory of us as a couple?",
        "How do you express love and affection?",
        "What does forever mean to you in the context of our relationship?",
        "How do you navigate expressing love during challenging times?",
        "What role does romance play in our relationship?",
        "Do you believe in soulmates, and if so, do you think we are soulmates?",
        "How do you handle differences in love languages?",
        "In what ways do you envision growing old together?",
        "What is your communication style, and how can we improve our communication as a couple?",
        "How do you handle misunderstandings and conflicts?",
        "What topics do you feel are off-limits or sensitive in our conversations?",
        "How do you feel about our communication through technology (texting, social media, etc.)?",
        "What are your thoughts on having regular check-ins to discuss our relationship?",
        "How do you prefer to express needs and expectations in a relationship?",
        "What is the most important aspect of effective communication for you?",
        "How do you feel about giving and receiving constructive feedback in our relationship?",
        "What can we do to create a safe and open space for honest communication?",
        "How do you feel about the balance between talking and listening in our conversations?",
        "How do you envision the division of roles and responsibilities in our relationship?",
        "What are your expectations regarding financial matters in a relationship?",
        "How do you feel about each other's independence and personal space?",
        "What role do trust and transparency play in our relationship?",
        "How do you handle decision-making within the relationship?",
        "What are your thoughts on compromise versus staying true to oneself?",
        "How do you maintain a healthy balance between individual goals and shared aspirations?",
        "How do you support each other's personal and professional growth?",
        "What traditions or rituals do you want to establish in our relationship?",
        "How do you envision our roles evolving as we navigate different life stages?",
        "What is the importance of maintaining friendships outside of our relationship?",
        "How do you feel about spending time with each other's friends?",
        "What qualities do you value most in a friend, and do we share those values?",
        "How do you handle conflicts or disagreements with friends?",
        "How do you feel about socializing as a couple versus spending time alone together?",
        "What role do friends play in providing emotional support in our lives?",
        "How do you navigate balancing social commitments and alone time?",
        "What activities or hobbies do you envision enjoying together with friends?",
        "How do you feel about making new friends as a couple?",
        "How can we support each other in maintaining and nurturing our individual friendships?",
        "How do you view personal growth within a relationship?",
        "What are your individual aspirations and dreams?",
        "In what ways do you think our past experiences and relationships may influence our present relationship?",
        "How do you prioritize self-care, and what can we do to ensure we both maintain a healthy balance?",
        "How do you cope with stress and adversity, and how can we support each other during challenging times?",
        "What role do personal values and beliefs play in your self-identity?",
        "How can we encourage and support each other's individual development?",
        "What fears or insecurities do you have, and how can we navigate them together?",
        "How do you feel about seeking external support, such as therapy or counseling, for personal growth?",
        "What steps can we take to maintain a sense of individual identity within our partnership?",
        "What are your favorite activities to do together?",
        "How do you feel about spontaneity versus planned activities in our relationship?",
        "What kind of vacations or travel experiences do you envision enjoying together?",
        "How can we incorporate laughter and playfulness into our daily lives?",
        "What hobbies or interests do you want to explore together?",
        "How do you feel about trying new things as a couple?",
        "What kind of entertainment do you enjoy, and how can we incorporate it into our lives?",
        "How do you handle downtime or moments of relaxation together?",
        "How can we maintain a sense of adventure and excitement in our relationship?",
        "What role do shared interests play in our connection?",
        "How do you define intimacy in our relationship?",
        "What are your needs and desires when it comes to physical affection?",
        "How do you feel about maintaining intimacy in long-term relationships?",
        "What role does emotional intimacy play in our connection?",
        "How do you approach initiating and expressing physical intimacy?",
        "How can we ensure that our intimate life stays fulfilling and satisfying?",
        "What are your thoughts on maintaining a healthy balance between physical and emotional intimacy?",
        "How do you feel about experimenting and trying new things in our intimate life?",
        "How can we create a sense of emotional closeness during busy or stressful times?",
        "How do you handle any insecurities or concerns related to intimacy in our relationship?",
        "What have been the most significant milestones in our relationship so far?",
        "How do you feel we have grown as a couple since we first met?",
        "What challenges have we faced together, and how did we overcome them?",
        "How has our relationship influenced your personal growth and development?",
        "What are your favorite qualities in each other?",
        "How do you feel we handle disagreements or conflicts, and what can we improve?",
        "How do you see us evolving as a couple in the future?",
        "What do you think are the strengths of our relationship?",
        "How do you feel about our ability to adapt to change as a couple?",
        "What are your hopes and dreams for our relationship moving forward?",
        "If you could go back to any moment in our relationship, which one would it be and why?",
        "What is your favorite thing about the way we communicate with each other?",
        "If our relationship had a theme song, what would it be?",
        "What do you think is the most underrated quality?",
        "Will you lick my balls if I wanted you to?",
        "Will you bite my lips when we kiss?",
        "Do you like when I choke you?",
        "Do you love it when I pull your hair back?",
        "Do you like it when I go rough on you?",
        "Can I smell your panties?",
        "Can I put some alcohol down there, and lick it?",
        "Do you like to go all the way in while kissing?",
        "What color underwear would you like to see me in?",
        "Where did you see a naked lady for the first time?",
        "Have you ever gotten a handjob in a park?",
        "What is the wildest thought you’ve had about me?",
        "Do you like to hold your partner from the front or back while making out?",
        "Where do your hands lay first on your partner’s body when you start kissing?",
        "Have you ever had a rough makeout session in a hotel room?",
        "Have you ever made out in the elevator?",
        "How long is your ****?",
        "Do you like your ass getting licked?",
        "How many sex positions have you tried till now?",
        "What is your go-to sex position after a tiring workday?",
        "Do you like to bite on my nipples?",
        "Would you like to cum on my face?",
        "Would you love to do doggy style with me?",
        "Do you want me to be a good girl in bed?",
    },
    sensualus = {
        "If you were to accidentally see someone naked, would you keep looking, or look away?",
        "What is your best pickup line?",
        "Would you kiss a total stranger?",
        "Have you ever been skinny-dipping? Where?",
        "Have you ever cheated in a relationship?",
        "Have you ever been cheated on in a relationship?",
        "What is your favorite date night activity?",
        "Do you believe in monogomy?",
        "Do you believe in polyamory or open relationships?",
        "What's something that you'd like to try, but have been too scared to try?",
        "What do you like to do most when you are alone?",
        "How do you feel about manscaping ?",
        "How do you feel about PDA (public displays of affection)?",
        "Have you ever had a one night stand?",
        "Which do you find sexier on a guy? Boxers or briefs?",
        "Which do you find sexier on a girl? Lace panties or a thong?",
        "What part of the body do you find most attractive?",
        "Do you prefer someone be waxed, trimmed or natural?",
        "What do you wear to sleep?",
        "Would you rather have a lover that is romantic, or freaky?",
        "Have you ever called a lover by the wrong name?",
        "Have you ever taken thirst trap pics of yourself?",
        "Would you rather have a hookup, or a relationship?",
        "What color underwear are you wearing?",
        "What type of underwear are you wearing?",
        "Do you like to give or receive backrubs?",
        "Have you ever had a hookup with a friend?",
        "Have you ever been to a nude beach?",
        "Who did you share your most memorable kiss with?",
        "Would you like someone to watch you when you are masturbating?",
        "Which sex position is the most underrated one?",
        "Are you a virgin?",
        "Do you like to use your tongue when you kiss?",
        "What is the best thing to lick from your partner’s body?",
        "Have you ever played dirty truth games with anyone?",
        "Do you like getting a blowjob?",
        "When was the last time you gave a handjob?",
        "Do you like making out in public places?",
        "What turns you on the most?",
        "What is your favorite type of lingerie?",
        "When was the last time you made out?",
        "Which is your go-to place to have sex?",
        "Have you ever ripped the condom from your teeth?",
        "Do you like to dirty talk in the bedroom?",
        "What is your favorite make-out spot?",
        "Where do you touch first when you start kissing?",
        "Do you like oral sex?",
        "Have you ever watched porn in a public place?",
        "How often do you touch yourself?",
        "Do you feel horny right now?",
        "When was the last time you received a blowjob?",
        "What is the maximum number of times you’ve had sex in 24 hours?",
        "What are the best emojis you use in a sex chat?",
        "What is your wildest sexual desire?",
        "Have you ever received a blowjob from a complete stranger?",
        "Would you be friends with benefits with anyone from this group?",
        "What is the most difficult sex position you did ?",
        "Do you like people watching you having sex?",
        "Have you ever been part of group sex?",
        "Do you like touching your partner’s private parts in public space?",
        "How many times can you cum in a session?",
        "Who will you choose to make out in the bathroom right now?",
        "Have you ever had sex with different people on the same day?",
        "Do you like to moan loud?",
        "What is the one guaranteed place you are going to kiss while having sex? (apart from lips)",
        "Have you ever masturbated in the public washroom?",
        "Who is your favorite porn star?",
        "How long is your ****?",
        "Do you like your ass getting licked?",
        "How many sex positions have you tried till now?",
        "What is your go-to sex position after a tiring workday?",
        "Have you ever fantasized about your friends of the opposite gender?",
        "What part of your body are you most confident about?",
        "Which is the one position you absolutely love to do?",
        "What should a person wear to turn you on?",
        "Have you ever made out when you were totally drunk?",
        "Have you ever made out in a classroom?",
        "Have you ever got horny seeing a celebrity half-naked online?",
        "Describe the last sex dream you had?",
        "What songs are definitely going to put you in the mood?",
        "What is the wildest place to make someone horny?",
        "What is the perfect line to make someone know that you are horny?",
        "Which is the best flavor of condom we have used to date?",
        "Does watching other people have sex turn you on?",
        "Have you ever had sex so loud the neighbors had to intervene?",
        "Have you ever walked in when a couple was doing it?",
        "Have you ever tried to dirty talk with the same gender?",
        "Have you ever paid to get a porn subscription?",
        "Have you ever had sex with two people who were friends with each other?",
        "How many hickies do you have on your body right now?",
        "Have you ever been friends with benefits with anyone?",
        "Have you ever gone to a nude beach?",
        "Have you ever had sex with anyone who was double your size?",
        "Who do you notice, when you are watching porn?",
        "Have you done it without shaving?",
        "Have you ever borrowed a costume for role-playing?",
        "What was the last dirty thing you searched on your phone?",
        "If you and your best friend are in the same situation, who do you think has the better chances of getting laid?",
        "Who else has seen you naked apart from the person you were in a relationship with?",
        "What is the craziest thing you have done to attract your crush towards you?",
        "How old were you when you had your first sex dream?",
        "How many times do you watch porn in a week?",
        "Have you ever touched your private parts in public, and no one noticed?",
        "Have you ever been sexually attracted to anime characters?",
        "How many times have you faked an orgasm?",
        "Have you ever had sex with a stranger?",
        "What are the top 3 things we will find if we went through your search history right now?",
        "What is the one sex position on your bucket list?",
        "Do you notice how a person eats a banana?",
        "List 3 sex kinks you have",
        "Have you ever gotten nervous before sex?",
        "Have you ever caught random strangers making out in public?",
        "Have you ever had sex with someone just because you were horny?",
        "What is the best sex toy ever made according to you?",
        "Have you ever kissed without brushing your teeth?",
        "Have you ever smelled the armpits of your partner?",
        "Have you ever had a one-night stand with your friend’s ex?",
        "Has the condom ever broken before sex?",
        "Has any of your friends ever caught you making moaning noises on the phone?",
        "What is the best way to fake an orgasm?",
        "Have you ever mistakenly sent a dirty text to the wrong person?",
        "Have you ever been abandoned in the middle of a sex session?",
        "Have any of your friends caught you touching yourself?",
        "Can you remember your weirdest sexual experience?",
        "Have you ever watched anime porn?",
        "Have you ever licked the body fluid that tasted extremely weird?",
        "Have you ever said I love you to someone only after making out with them 3 times?",
        "Have you ever acted in a sex position in a public gathering?",
        "Which celebrity couple would you choose to have a threesome with?",
        "Have you ever experienced a squirting orgasm?",
        "What is the dirtiest thing you ever thought of doing with your partner?",
        "Has the penis ever touched the end of the vagina?",
        "Have you ever rubbed your cum on your partner’s face?",
        "Have you ever spit on your partner?",
        "Do you like to suck on nipples?",
        "Have you ever done it in a group?",
        "Have you ever done it without shaving it down there?",
        "What is your favorite body part to lick ice cream from?",
        "Do you like it when talking is involved during sex?",
        "Are you fond of second rounds?",
        "Does teasing make you horny?",
        "Can you resist the temptation to want sex?",
        "Do you like being romantic when you are having sex?",
        "Do you like to talk about what you want to do to your partner in the bedroom?",
        "Who is the dirtiest in the group?",
        "Who in the group will have sex just to get a job?",
        "Who in the group was the first one to have sex?",
        "Who in the group was the freakiest one in school?",
        "Who in the group was the first to get an oral?",
        "Who in the grouphas kissed their exes after breaking up?",
        "Who in the group is the first one to have a one-night stand?",
        "Who in the groupis most likely to go for skinny dipping?",
        "Who in the group has the potential to become a porn star?",
        "Who in the group is going to have sex with their boss?",
        "Who in the group  has a hair fetish?",
        "Who in the group is the biggest pervert?",
        "Who in the group  has received the maximum number of dick pics?",
        "Who in the group  here has never used a condom for sex?",
        "Who in the group  has done BDSM?",
        "Who in the group  has got the largest compliments for their hot body?",
        "Who in the group  here prefers phone sex than physical sex?",
        "Who in the group  has the hottest ass here?",
        "Who in the group  has never done it in a car ever?",
        "Who in the group  is most horny right now?",
        "If you had to choose someone from this group to have sex with, who will you choose?",
        "Who was the person who gave you your first orgasm?",
        "Did you ever have sex with someone while being in a relationship with someone else?",
        "Have you ever shaved your partner’s pubic hair?",
        "What nickname have you given to your partner’s private parts?",
        "Have you ever farted while doing it?",
        "Which one of your neighbors would you love to sleep with?",
        "Are you okay with people watching you making out in a public place?",
        "Can you moan for 5 hours, if the sex happens that long?",
        "When was the time you really felt embarrassed about your size?",
        "When was the last time you were naked?",
        "Do you get horny seeing a condom ad?",
        "Have you ever been a sex partner to someone who was in a relationship?",
        "If you were into same-sex, which celebrity would you have sex with?",
        "What is the strangest role-play you have ever done?",
        "What do you love most about foreplay?",
        "How was your first sexual experience? Did it happen exactly how you thought?",
        "Have you ever heard your parents doing it?",
        "Who do you think has the nicest butt among all your friends?",
        "How many people have you kissed to date?",
        "Name the last person you had oral with?",
        "Have you ever flashed a bartender for a free drink?",
        "Have you ever had a one-night stand with a band member?",
        "Let someone put a hand on your thigh for the rest of the game?",
        "Show us what underwear you are wearing right now?",
        "Name the ex you had the most amazing sex with?",
        "Who is the oldest person you have flirted with?",
        "Who is the one person you didn’t enjoy sex with?",
        "What is the most embarrassing place you got horny?",
        "Are you fully satisfied with your sex life right now?",
        "Who do you want to see naked right now?",
        "What is the naughtiest thing you have done in public?",
        "Who is the oldest person you have made out with?",
        "What is the silliest reason you have used for not sleeping with someone?",
        "What sex position you’ve never tried?",
        "What is the dirtiest text you’ve ever received from a stranger?",
        "Have you ever been to a strip club?",
        "Have you ever watched gay porn?",
        "Have you ever practiced kissing in front of the mirror?",
    },
    truthordare = {
        truth = {
            "What is the most embarrassing thing that has happened to you in the past year?",
            "Have you ever told a lie to get out of trouble, and if so, what was it?",
            "If you could switch lives with someone for a day, who would it be and why?",
            "What is a secret talent or skill that you have that not many people know about?",
            "What is your biggest fear, and why does it scare you?",
            "If you could go back in time and change one decision you've made, what would it be?",
            "Have you ever had a crush on someone in this room? If so, who?",
            "What is the weirdest dream you've ever had?",
            "If you had to eat only one type of food for the rest of your life, what would it be?",
            "Have you ever cheated on a test or exam?",
            "What's the most unusual or unique thing you've ever eaten?",
            "Have you ever had a crush on a fictional character, and if so, who?",
            "If you could have any superpower, what would it be and how would you use it?",
            "What's the most adventurous thing you've ever done or would like to do?",
            "What is a guilty pleasure of yours that you usually keep hidden?",
            "If you were stranded on a deserted island, and you could only bring three items, what would they be?",
            "What's the most embarrassing nickname you've ever had?",
            "Describe your weirdest or most irrational fear.",
            "If you could trade lives with someone for a week, who would it be and why?",
            "What's the most spontaneous thing you've ever done?",
            "Are you a virgin?",
            "Do you like to use your tongue when you kiss?",
            "What is the best thing to lick from your partner’s body?",
            "Have you ever played dirty truth games with anyone?",
            "Do you like getting a blowjob?",
            "When was the last time you gave a handjob?",
            "Do you like making out in public places?",
            "What turns you on the most?",
            "What is your favorite type of lingerie?",
            "When was the last time you made out?",
            "Which is your go-to place to have sex?",
            "Have you ever ripped the condom from your teeth?",
            "Do you like to dirty talk in the bedroom?",
            "What is your favorite make-out spot?",
            "Where do you touch first when you start kissing?",
            "Do you like oral sex?",
            "Have you ever watched porn in a public place?",
            "How often do you touch yourself?",
            "Do you feel horny right now?",
            "When was the last time you received a blowjob?",
            "What is the maximum number of times you’ve had sex in 24 hours?",
            "What are the best emojis you use in a sex chat?",
            "Have any of you sent your nude selfie before coming here?",
            "How was the elevator ride? (catch the smirks, and then play your cards)",
            "What is your wildest sexual desire?",
            "Are you the explorer type in the bedroom?",
            "Have you ever received a blowjob from a complete stranger?",
            "Would you be friends with benefits with anyone from this group?",
            "What is the most difficult sex position you did in your car?",
            "Have you ever been in open relationships?",
            "How many can you take in your mouth in one go?",
            "Do you like people watching you having sex?",
            "Have you ever been part of group sex?",
            "Do you like touching your partner’s private parts in public space?",
            "How many times can you cum in a session?",
            "Who will you choose to make out in the bathroom right now?",
            "Is having sex while still wearing underwear wilder?",
            "From whose mouth would you like to sip alcohol?",
            "Have you ever tried to do a hardcore session?",
            "Have you ever had sex with different people on the same day?",
            "Do you like the French kiss?",
            "Do you like to go gentle while kissing?",
            "How old were you when you lost your virginity?",
            "What is your favorite part to be kissed?",
            "What porn do you watch if you feel like masturbating?",
            "Have you ever made out in a college cafeteria?",
            "Do you like to moan loud?",
            "Do you like to sit on your lap while you are making out?",
            "Do you bite your lip if you are horny?",
            "Which celebrity would you not mind having a one-night stand with?",
            "Have you ever rubbed your nipple when you were alone?",
            "Have you ever clicked your nude pictures to see how it looks?",
            "How many fingers did you try to put inside when you were masturbating for the first time?",
            "Have you ever read erotic novels?",
            "Does size matter to you?",
            "Have you ever worn a slutty dress to seduce someone?",
            "Have you ever hit on your brother/cousin’s friends?",
            "Have you ever tried to check a guy’s dick through his pants?",
            "Have you ever done it in a cinema hall?",
            "Will you be up for a make-out session if I ask you to?",
            "What is your favorite position to give a blowjob?",
            "Do you want me to unhook your bra with one hand?",
            "Would you step out in public without wearing underpants if I asked you to?",
            "Do you like to close your eyes when I kiss all over your body?",
            "Do you want me to give you lots of love bites under your breasts?",
            "Would you let me push you against the wall and make out with you?",
            "Do you love doing a mouth-fuck?",
            "Can you take 3 fingers inside?",
            "Will you lick my balls if I wanted you to?",
            "Will you bite my lips when we kiss?",
            "Do you like when I choke you?",
            "Do you love it when I pull your hair back?",
            "Do you like it when I go rough on you?",
            "Can I smell your panties?",
            "Can I put some alcohol down there, and lick it?",
            "What is the one guaranteed place you are going to kiss while having sex? (apart from lips)",
            "Have you ever masturbated in the public washroom?",
            "Who is your favorite porn star?",
            "What do you wear to bed if you are in the mood?",
            "Which part of a woman do you notice first?",
            "Have you ever secretly touched someone’s private parts and liked how it felt?",
            "Have you ever checked out a girl in a bikini?",
            "Do you like to go all the way in while kissing?",
            "What color underwear would you like to see me in?",
            "Where did you see a naked lady for the first time?",
            "Have you ever gotten a handjob in a park?",
            "What is the wildest thought you’ve had about me?",
            "Do you like to hold your partner from the front or back while making out?",
            "Where do your hands lay first on your partner’s body when you start kissing?",
            "Have you ever had a rough makeout session in a hotel room?",
            "Have you ever made out in the elevator?",
            "How long is your dick?",
            "Do you like your ass getting licked?",
            "How many sex positions have you tried till now?",
            "What is your go-to sex position after a tiring workday?",
            "When was the last time you felt like you were not yourself?",
            "What is your most favorite position for yoga?",
            "When was the last time you had a crazy one-night stand and why was it crazy?",
            "What is your most favorite memory of sex?",
            "What was your most electrifying touch in your life and why?",
            "What is the weirdest thing you have done with your partner?",
            "Is there any late-night incident that you think can never happen to anyone else?",
            "Do you have any sexual memory that you believe nothing can beat ever?"
        },
        dare = {
            "Dance like nobody's watching for the next two minutes.",
            "Send a banana emoji to the third person in your contact list and read their answer",
            "Speak in an accent of your choice for the next three rounds.",
            "Go to a starnger and shout I am a superhero  as loud as you can.",
            "Post a funny status or picture on your social media account.",
            "Sing a song of the group's choice at the top of your lungs.",
            "Do your best animal impression for the next two minutes.",
            "Text your crush (or someone you haven't spoken to in a while) and say something random.",
            "Dance a striptease to a song of my choosing. ",
            "Seduce me using your best sexy quotes",
            "Do your best impression of a famous cartoon character.",
            "Do 10 jumping jacks while reciting a tongue twister.",
            "Text your ex with an outrageous compliment",
            "Find a random object in the room and create a short commercial to sell it.",
            "Create a funny and fictional story about how you got your current job.",
            "Call a friend and sing Happy Birthday  to them, even if it's not their birthday.",
            "Perform a short stand-up comedy routine for the group.",
            "Do your best impression of a famous movie character.",
            "Share a funny or embarrassing moment from your past.",
            "Send a compliment to the fifth person in your contact list.",
            "Create a short rap about the last thing you ate.",
            "Pick someone and flirt to the person",
            "Send a funny meme or GIF to the first person in your contact list.",
            "Serenade another while falling to your knees.",
            "Do your best impression of a baby being born.",
            "Beg and plead the person to your right not to leave you.",
            "Give a piggyback ride to the person on your left.",
            "Read the last 5 text messages on your phone.",
            "Read your ex last message",
            "Argue with the couch for 5 minutes.",
            "Call someone and ask for 5 cents to borrow",
            "Call your best friend and tell him(her) that you are engaged",
            "Whisper a secret in my ear.",
            "Hit on me like you don’t know me.",
            "Try to turn me on without touching me.",
            "Give me a lapdance.",
            "Let me spank you 10 times.",
            "Take off your shirt",
            "Take off your pants",
            "Take off your shoes",
            "FaceTime someone and say you are in love with",
        }
    }
}
