-- Auto-generated by gw-anim-editor
-- Resource : blood_draw_medic
-- Dict     : blood_draw_medic@anim        (file stream/blood_draw_medic@anim.ycd)
-- Clip     : blood_draw_medic        (internal Hash inside the .ycd)

local DICT = 'blood_draw_medic@anim'
local ANIM = 'blood_draw_medic'

-- TaskPlayAnim flag combos worth trying if /test_animation looks off :
--   1   = AF_LOOPING                   (basic loop, default here)
--   2   = AF_HOLD_LAST_FRAME           (plays once + holds at last frame)
--   49  = AF_LOOPING + UPPERBODY + SECONDARY  (overlay on idle)
local DEFAULT_FLAG = 1

local function loadAnimDict(d)
    if HasAnimDictLoaded(d) then return true end
    RequestAnimDict(d)
    local tries = 0
    while not HasAnimDictLoaded(d) and tries < 200 do
        Wait(10)
        tries = tries + 1
    end
    return HasAnimDictLoaded(d)
end

local function playPose(flag)
    local ped = PlayerPedId()
    local res = GetCurrentResourceName()
    flag = flag or DEFAULT_FLAG

    if not loadAnimDict(DICT) then
        print(('[%s] [FAIL] dict %q not loaded - is %s.ycd in /stream/ ?'):format(res, DICT, DICT))
        return
    end

    ClearPedTasksImmediately(ped)
    Wait(50)
    TaskPlayAnim(ped, DICT, ANIM, 8.0, -8.0, -1, flag, 0.0, false, false, false)
    Wait(150)

    if IsEntityPlayingAnim(ped, DICT, ANIM, 3) then
        print(('[%s] [OK] playing %s/%s (flag=%d)'):format(res, DICT, ANIM, flag))
    else
        print(('[%s] [FAIL] engine rejected %s/%s - try /test_animation 2 or 49'):format(res, DICT, ANIM))
    end
end

RegisterCommand('test_animation', function(_source, args)
    local flag = tonumber(args[1]) or DEFAULT_FLAG
    playPose(flag)
end, false)

RegisterCommand('stop_animation', function()
    ClearPedTasksImmediately(PlayerPedId())
    print(('[%s] cleared tasks'):format(GetCurrentResourceName()))
end, false)

RegisterCommand('debug_animation', function()
    local ped = PlayerPedId()
    local res = GetCurrentResourceName()
    print(('[%s] === debug ==='):format(res))
    print(('[%s] DICT       = %q'):format(res, DICT))
    print(('[%s] ANIM       = %q'):format(res, ANIM))
    print(('[%s] dict loaded= %s'):format(res, tostring(HasAnimDictLoaded(DICT))))
    print(('[%s] playing    = %s'):format(res, tostring(IsEntityPlayingAnim(ped, DICT, ANIM, 3))))
end, false)

CreateThread(function()
    Wait(500)
    local res = GetCurrentResourceName()
    print(('[%s] ready : %s/%s'):format(res, DICT, ANIM))
    print(('[%s] commands : /test_animation [flag]  /stop_animation  /debug_animation'):format(res))
end)
